#!/usr/bin/env bash

check_factor() {
    if [ $# -ne 3 ]; then
        args=("$@")
        count=0
        num2=1
        for a in "${args[@]}"; do
            if [ $count -gt 1 ]; then
                num2=$((a * num2))
            fi
            count=$((count + 1))
        done
    else
        num2=$3
    fi

    num1=$2

    if [ "$num2" -gt "$num1" ]; then
        temp=$num1
        num1=$num2
        num2=$temp
    fi

    echo -n "$1=$num1*$num2"
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
else
    while read -r i; do
        result=$(factor "$i" | awk '{print $2 " " $3}')
        check_factor "$i" $result
        echo
    done < "$1"
fi
